### ISSUE TITLE
MvpDelegateCallback does not exist

### ISSUE THREAD

**Issue by vovkab** [sockeqwe/mosby#101]
Version: Mosby v2.0.0:

According to documentation here:
http://hannesdorfmann.com/mosby/mvp/

There should be `MvpDelegateCallback`:

> MvpDelegateCallback: Is an interface every MvpView in Mosby has to implement. Basically it just provides some MVP related methods like

Instead all delegate classes uses `BaseMvpDelegateCallback<V, P>`

**Comment by sockeqwe** [comment]
You are right, the documentation is not up-to-date on this.
MvpDelegateCallback has been renamed to BaseMvpDelegateCallback in Mosby 2.0

I will update the docs.
thanks for reporting!

Vladimir Baryshnikov <notifications@github.com> schrieb am Do., 19. Nov.
2015 22:56:

**Comment by vovkab** [comment]
Thanks for quick response!

Btw, any reason why it should be `Base` and not the one in documentation?

**Comment by sockeqwe** [comment]
Because in Version 2 I had to introduce ActivityNvpDegateCallback extends
BaseDelegateCallback and ViewGroupNvpCallback extends  BaseDelegateCallback
with some more some more specific methods for activity / viewgroup. I have
noticed that only Fragments use BaseDelegateCallback directly, for
consistency I should b introduce a FragnentDelegateCallback extends
BaseDelegateCallback
as well I guess

See documentation for all subclasses
http://hannesdorfmann.com/mosby/static/javadoc/com/hannesdorfmann/mosby/mvp/delegate/BaseMvpDelegateCallback.html

As already said this part of the documentation is needs an update

Vladimir Baryshnikov <notifications@github.com> schrieb am Do., 19. Nov.
2015 23:03:

**Comment by vovkab** [comment]
As I can see it only have 2 direct interfaces that extend it:
BaseDelegateCallback:
-- ActivityMvpDelegateCallback
-- BaseMvpViewStateDelegateCallback

imo, old version would look much nicer without `Base` :)
Something like:
MvpDelegateCallback:
-- ActivityMvpDelegateCallback
-- ViewStateMvpDelegateCallback

but it is up to you, just my 2cents...

Unrelated question. Right now as I can see you are creating presenter in `onViewCreated`, but if you have fragment in your layout.xml file this probably will crash if you use something that is not yet created, to create your presenter. Let me know I can pull it into separate issue.

**Comment by sockeqwe** [comment]
You are right, without `Base` it is definetly nicer. To be honest I can't remember what exactly the reason was to introduce `Base` as prefix. I will check the class hierarchy and check for the related git commit messages. maybe I guess I had a good reason for introducing `Base`, but can't remember why :smile:  or have changed opinion after having renamed it to `Base` but forgot to remove the `Base` prefix.

I will investigate on that.


Regarding `onViewCreated()`: Yes, please open another issue for that. Makes it easier for others to follow the discussion and avoids confusing sub-threads

**Comment by Tiny-Times** [comment]
want to know why there is a need to use weak references.

public abstract class MvpBasePresenter<V extends MvpView> implements MvpPresenter<V> {
    private WeakReference<V> viewRef;
    @Override
    public void attachView(V view) {  }
    protected V getView() { }
    protected boolean isViewAttached() {  }
    @Override
    public void detachView(boolean retainInstance) {   }
}

activity：When press the return key, “ondestory” is sure to be executed, so the “detachView” will be executed.

**Comment by sockeqwe** [comment]
Renamed in 3.0
