### ISSUE TITLE
Connect an RxSearchView with a MvpLceView - MvpLceRxPresenter

### ISSUE THREAD

**Issue by jjvargas** [sockeqwe/mosby#105]
I have this code on my view that implements MvpLceVIew ,  so the searchView reacts to the text change making a search to a catalog, the search part should be on the presenter that then will call subscribe(Observable<M> observable, final boolean pullToRefresh) which will call show() to update the UI. 

queryTextChanges return an Observable but I dont really know how to connect the search observable this with the MvpLceView/MvpLceRxPresenter architecture. any idea?

                    RxSearchView.queryTextChanges(searchView).
                                    filter(charSequence ->
                                            !TextUtils.isEmpty(charSequence))
                                    .throttleLast(100, TimeUnit.DAYS.MILLISECONDS)
                                    .debounce(200, TimeUnit.MILLISECONDS)
                                    .onBackpressureLatest()
                                    .concatMapEager(searchTerm ->
                    
                             //returns search observable - this should be in the presenter then call subscribe()
                                            MarsCoordinator.getClientCoordinator().getRxV1Service().
                                getSearchResourceItemsFromCatalog(false, 0, 50, IRxV1Service.GetSearchResourceItemsFromCatalogRight.RADIO, null, searchTerm.toString().trim(), null)
                                .subscribeOn(Schedulers.io())
                                .onErrorResumeNext(throwable1 -> {
                                            //handle error somehow, change UI
                                            return Observable.empty();
                                        }

                                )
                )
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(searchResults -> {

                    //POPULATE UI WITH SEARCH RESULTS
                    //THIS SHOULD BE DONE IN THE SHOW()

                }, throwable -> {

                    Toast.makeText(getContext(), throwable.getMessage(), Toast.LENGTH_SHORT).show();
                });

**Comment by sockeqwe** [comment]
Hi, I will take time tomorrow to write down my thoughts on this ...

**Comment by jjvargas** [comment]
Thanks

**Comment by sockeqwe** [comment]
Sorry for my delayed answer.
Ok I think there are 2 ways to deal with that: 

- Simply call corresponding presenter method in `onNext()` like this:
```java
RxSearchView.queryTextChanges(searchView).
                                filter(charSequence ->
                                        !TextUtils.isEmpty(charSequence))
                                .throttleLast(100, TimeUnit.DAYS.MILLISECONDS)
                                .debounce(200, TimeUnit.MILLISECONDS)
                                .onBackpressureLatest()
                                .subscribe( searchTerm -> presenter.search(searchTerm) );
```

and then the presenter creates his own Observable to exectute the search:
```java
class SearchPresenter extends MvpBasePresenter { 

    public void search(String searchTerm) {
         MarsCoordinator.getClientCoordinator().getRxV1Service().
                            getSearchResourceItemsFromCatalog(false, 0, 50, IRxV1Service.GetSearchResourceItemsFromCatalogRight.RADIO, null, searchTerm.toString().trim(), null) // Assuming this returns an Observable
         .observeOn( ... )
         .subscribeOn( ... )
         .subscribe(
             searchResults ->  getView().showResult(searchResult) , 
             throwable -> getView().showError(throwable)
          );
    }
}
```
The problem with this approach is that we are kind of breaking the reactive observable chain since we split it in two observables (on in the View  `RxSearchView.queryTextChanges` and one in presenter `presenter.search()` ). I will discuss the advantages  / disadvantages in a minute.

- Working with one single Observable chain by returning an observable like from the view like this:
```java
interface SearchView extends MvpView {
     Observable<String> getSearchInputObservable();

     void showResult(SearchResult result);
     void showError(Throwable error);
}
```

```java
class SearchViewActivity extends MvpActivtiy implements SearchView {
    ...
    @Override
    public Observable<String> getSearchInputObservable() {
        return RxSearchView.queryTextChanges(searchView).
                                filter(charSequence ->
                                        !TextUtils.isEmpty(charSequence))
                                .throttleLast(100, TimeUnit.DAYS.MILLISECONDS)
                                .debounce(200, TimeUnit.MILLISECONDS)
                                .onBackpressureLatest();
     }
}
```

```java
class SearchPresenter extends MvpBasePresenter<SearchView> {
   @Override
   public void attachView(SearchView view){
       super.attachView(view);
       view.getSearchInputObservable()
              .flatMap(searchTerm -> MarsCoordinator.getClientCoordinator().getRxV1Service().
                            getSearchResourceItemsFromCatalog( ... , searchTerm) ) // returns an Observable <SearchResult> 
              .subscribeOn(...)
              .observeOn(...)
              .subscribe(
                searchResults ->  getView().showResult(searchResult) , 
                throwable -> getView().showError(throwable)
               );
   }
}
```

So with the second approach we have a single Observable chain. When the view gets attached to the presenter we take the observable from the view ( `view.getSearchInputObservable()`) and use `flatMap` to "transform" the view's `Observable<String>` (which provides the searchTerm) to `Observable<SearchResult>` from ( `getSearchResourceItemsFromCatalog()` ).
So this seems to be a nice solution since the view emits the searchTerm (and any update of the searchTerm) to the presenter which then executes the search result. We have one single observable chain. View and Presenter are still separated (presenter doesn't know how the searchTerm is created, view is still independent i.e. you can change a TextView to another UI widget without having to change the presenters code as long as the other UI Widget provides `Observable<String>`). So this might be the solution you are looking for, right?

So lets discuss both solutions: The main difference between both solutions is that the first breaks the single observable chain into two distinct Observables and Subscriptions whereas the second solution is one single observable flow. 

**BUT**

with the second the single observable chain is tight to the View's lifecycle. This means when the view get's destroyed the whole observable gets unsubscribed. This isn't a bad thing per se, but with Mosby the Presenter can survive screen orientation changes and the single Observable chain discussed in the second aproach will break that. Mosby's design philosophy is to attach and detach the view from Presenter during screen orientation changes:

1. User launches app --> PortraitView gets instantiated --> PortraitPresenter gets created
2. User rotates device from portrait to landscape  --> PortraitPresenter stays alive (any ascny running task don't have to be canceled) ; PortraitView gets detached from PortraitPresenter.
3. LandscapeView gets instantiated --> LandscapeView get attached to PortraitPresenter (still same presenter instance as in portrait)

But with the single observable chain of the second aproach things are going like this:

1. User launches app --> PortraitView gets instantiated --> PortraitPresenter gets created 
2. User rotates device from portrait to landscape  --> PortraitPresenter could stay alive **BUT** all async running observable tasks are canceled (unsubscribed). Otherwise we have a memory leak. 
3. LandscapeView gets instantiated --> LandscapeView gets attached to PortraitPresenter **BUT** since all async running observable tasks has been canceled during screen orientation changes, new observable async running  tasks have to be established. That means that the search query started in portrait has to be restarted in landscape.

So is this a big disadvantage? It depends. Maybe, maybe not. If you are fine with the fact that:
 -  the View will be started completely new on each screen orientation change (as have been launched for the first time)  or if you want to have do all the boilerplate code to save the state manually in bundle and restore the state afterwards from bundle
- presenter is created newly on each screen orientation change and re-execute the search query again

(in other words don't use Mosby's ViewState feature that allows the views state and presenter to be retained during screen orientation changes and all async task are still ongoing) then I would say the second approach is a good solution.

Otherwise, I would go with the first approach.

I, personally, do most of the time the first approach. For me it's more important to don't have to deal with screen orientation changes manually. I also see the view just as Input / Output device which for me means I want to have one single observable chain from presenter downwards to business logic (http, database etc.) and the way back to presenter. So for me it's not a big deal to use rxjava in View for handling UI Events like ` RxSearchView.queryTextChanges()`  and Presenter on two  separated Observables. 
However, from an Rx workflow point of view the second approach is definetly nicer and cleaner.

We could also try to combine the best of both approaches first (SearchObservable is not bound to views lifecycle) and the second (on single Observable flow) by using RxJava's Subject (like `BehaviorSubject`) in presenter as kind of proxy. But this is an advanced Rx topic. 

Nevertheless, keep in mind that the important bit of MVP is to have a clean separation of concerns.

Hope that helps
