### ISSUE TITLE
Can I change view id?

### ISSUE THREAD

**Issue by thphuc** [sockeqwe/mosby#106]
Hi there,

I'm trying to read some Mosby document.
It is saying that some ids MUST be predefined ids like below:

"The loading view must have the id = R.id.loadingView"
or 
"The content view must have the id = R.id.contentView"

But in my team, we have used a different convention (for a long time) like this: R.id.loading_view or R.id.content_view. 
So in order to apply Mosby to our projects, we have to change our existing convention, is it correct?

**Comment by jvilya** [comment]
I think it is not necessarily.

Try to override the method `findViewById(ind id)` in your activity/fragment that extends Mosby's MvpLce* classes in next way:

    public View findViewById (int id) {
        if (id == R.id.loadingView) { // mosby's view id for loading
            return super.findViewById(R.id.loading_view); // your project's view id for loading
        }
        // same for contentView and errorView
        return super.findViewById(id);
    }

**Comment by sockeqwe** [comment]
Yes, Mosby LCE (Loading-Content-Error) has this "hardcoded" id's:

Fortunately, there is a simple workaround (undocumented, since it's not Mosby related, it's an android feature).

You can make "pointers" to other ids in xml. Just add a android resource file (name of the file doesn't matter) in your apps `res/values/` folder with the following content:

```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>

  <!-- Forwards R.id.loading_view to Mosby's R.id.loadingView -->
  <item name="loading_view" type="id">@id/loadingView</item> 
  
   <!-- Do the same for R.id.contentView and R.id.errorView -->

</resources>
```

Yes you have to include such a resource file in all your projects if you want to continue with your convention and Mosby.
Alternatively you could also make your own library with only the dependency to Mosby and then add this resource file as described above. Then build your library project as android library (`.aar`) and include your own library in all your projects. By doing so you have integrated mosby and the resource file with id "overriding" / "forwarding" with just one single dependency and you don't have to include the resource file from above in every single project.

Hope that helps

**Comment by thphuc** [comment]
Thanks @jvilya and @sockeqwe 
I will try
