### ISSUE TITLE
setPresenter should dettachView on the previous presenter and attach to the new if the view is attached

### ISSUE THREAD

**Issue by joseprl89** [sockeqwe/mosby#120]
I have noticed that if we update the presenter of an MvpFragment/MvpActivity/MvpLinearLayout... the setPresenter method does not have any logic to attach the view to the new presenter if the view is currently visible.

The reason for this is that I was considering switching the presenter to a different class (implementing the same interface) when entering into "edit" mode in a given screen.

However, I would need to handle the attach/dettach view manually which is something that feels error prone, and that could potentially be done by the MvpFragment and similar classes.

**Comment by sockeqwe** [comment]
hi,
I'm sorry but I'm not sure if I have understood you correctly.

What do you mean with "update the presenter"? You mean you have a View and change the "presenter" dynamically but the view still remains the same?

**Comment by joseprl89** [comment]
Sorry not to make it clear enough.

My point is that I have a view I want to switch to an "edit" mode. I could do with a single presenter, but I'd have to keep several conditions like "if state is edit, do this, else, do that".

I was wondering if I could set a different presenter when the view enters edit mode, that wait instead of having several conditions I'd just have two smaller independent presenters that could be unit tested separately.

Upon inspecting the setPresenter code given by MvpFragment amongst other, I noticed there's no logic to dettach the view from the previous presenter, and attach it to the new one. Hence this issue.

**Comment by sockeqwe** [comment]
I see, that makes sense. 
However, from my point of view that would change the View as well? In my opinion an entirely new `EditView` with his own `EditPresenter` should be visible on screen.

Otherwise your "single" view will have all that "if state is edit, do this, else, do that" (instead of the presenter).

**Comment by joseprl89** [comment]
I think we could avoid the if's by having the presenter notify an entirely different method. 


PS: I'll be busy this days on a business trip so I'm not sure If I'll manage to provide much more feedback :/

**Comment by sockeqwe** [comment]
I think this is not the default use case (and I still think a separated View and Presenter for edit mode is the cleaner approach), so I will not add support for that kind of feature you are asking for (setPresenter should dettachView() of previous Presenter and automatically bind the new presenter), because it will blow up the internal code and as already said, I think it's not the way things should be implemented.

However, there is another solution (already existing solution) which should work (not tested yet) that comes close to what you try to achieve.
Mosby provides an `ActivityMvpDelegate`, `FragmentMvpDelegate` and `ViewGroupMvpDelegate` and a corresponding `MvpDelegateCallback` you have to implement.

So what you can do is create two "ActivityMvpDelegate" container objects like this (imagine that there are View interfaces `NormalView`  and `EditView`):

```java
class MyActivity extends AppCompatActivity implements EditView, NormalView {
    
      private NormalViewDelegate normalViewDelegate;
      private EditViewDelegate editViewDelegate;

     void onCreate(Bundle b){
            super.onCreate(b);
            setContentView(R.layout.my_view_with_normal_and_edit_mode);
            normalViewDelegate = new NormalViewDelegate(this);
            editViewDelegate = new EditViewDelegate(this);

          normalViewDelegate.onCreate(b);
          editViewDelegate.onCreate(b);
      }

     void onDestroy(){
          super.onDestroy();
          normalViewDelegate.onDestroy();
          editViewDelegate.onDestroy();
     }

     ...  // also forward all other lifecycle callbacks like onResume() etc.
}
```

Then `EditViewDelegate` look like this:
```java
class EditViewDelegate implements <EditView, EditPresenter>, MvpDelegateCallback<EditView, EditPresenter> {
   ActivityMvpDelegate mosbyDelegate = new ActivityMvpDelegate<>(this);
   EditView editView;

   EditViewDelegate(EditView editView){
       this.editView = editView;
   }

  void onCreate(Bundle b){
        mobsyDelegate.onCreate(b);
   }

  void onDestroy(){
        mobsyDelegate.onDestroy();
   }

   ... // also forward other lifecycle events

   @Override   // MvpDelegateCallback method
   EditView getMvpView(){
       return editView;
    }

   @Override // MvpDelegateCallback method
   EditPresenter createPresenter() {
         return new EditPresenter();
    }

   ... // other MvpDelegateCallback methods
}
```

You also have to do the same for `NormalViewDelegate`. The trick here is that  `getMvpView()` is actually pointing to the parent activity, because the activity is implementing `EditView` and `NormalView` interface. The containers `NormalViewDelegate` and `EditViewDelegate` are just there to separate mosby's internal methods which otherwise would cause conflicts (because of generics) if they would be implemented directly in your Activity. 

With this aproach you will have two decoupled Presenter, "living" at the same time, programming agains a dedicated MvpView interface each, but still having one single layout file containig the components of both, NormalView and EditView.

Hope that helps!
