### ISSUE TITLE
Remove @Nullable from getView

### ISSUE THREAD

**Issue by PaulWoitaschek** [sockeqwe/mosby#123]
I find it very inconvenient that `getView()` is annotated as `@Nullable`.  
My presenters are full of yellow warnings.

I know what I'm doing and when I use the view I know that it is not null. Therefore I end up with suppressing constant conditions either class wide (by which I lose other annotations). Or I write an abstract class which overrides the `getView` and returns explicitly `@NonNull`.

So I want to propose to remove the annotation, like stated [by Google:](https://sites.google.com/a/android.com/tools/tech-docs/support-annotations)

> Only use @Nullable on a return value if you’re prepared to say that every use of the method should be explicitly null checked.  As a rule of thumb: Take a look at existing “good code” (e.g. code reviewed production code) to see how the API is being used.

**Comment by sockeqwe** [comment]
I feel your pain. But, actually per contract this method can return `null` and should be null checked, but typically you do that null check with `isViewAttached()`. I already thought about a custom LINT check #53  .
> I know what I'm doing and when I use the view I know that it is not null.

So why not writing your own Presenter. `MvpBasePresenter` is really not required (no magic), have a look at the [source code](https://github.com/sockeqwe/mosby/blob/master/mvp-common/src/main/java/com/hannesdorfmann/mosby/mvp/MvpBasePresenter.java)

Also the javadocs indicats:
>  So using a WeakReference and adding the isViewAttached() check are basically just some
  kind of safety net and not needed in a "perfect world". Please note that if you are sure that
  you are coding in such a "perfect world" then you can also think about implementing your own
  Presenterentirely without WeakReference and isViewAttached(). Note also that
  MvpPresenter is an interface. Hence implementing you own Presenter is easy.


So the presenter you are looking for is as simple as this:
```java
class IKnowWhatImDoingPresenter<V extends MvpView> implements Presenter<V> {

    protected V view;

   @Override public void attachView(V view) {
        this.view = view;
    }

  @Override 
  public void detachView(boolean retainInstance) {
     view = null
   }
}
```

Then you don't have a `getView()` at all and can access the `view` directly

**Comment by PaulWoitaschek** [comment]
Okay. The custom lint check could be helpful but in most of the cases you don't have to do a manual check if the view is attached.

I.e if you call the view in a presenter method that was called by the view, you're still on the UI Thread and thus you can skip the check. But yup, I'll make my own presenter.

Actually I have created a few classes I'm using that are almost similar to your solution but I want to participate on a larger library that is evolving.

**Comment by sockeqwe** [comment]
Thanks for your feedback. I really appreciate that and I think you are right in general, but theoretically view can be null i.e. if you have forgot to cancel an AsyncTask. I know that this is not the case for your and for my apps because we are advanced android developers. But I think for android beginners (and there are plenty who are using mosby) it's better do have this "safety net" and for them it might be useful to get an LINT / IDE warning if they don't check for view != null. However, as you have already said, there are for sure situations where you are entirely sure that the view cannot be null and those false warnings are annoying, also for beginners. 

So I will think about removing `@Nullable`, but I hope to find another solution for this annoying problem.

**Comment by mkoslacz** [comment]
Well, first of all, thanks for the golden shovel award for renewing this thread. 

I'm developing a viper extension for mosby and I have also encountered this annoying issue. The presenter code is covered in yellow warning highlights because of a lint guess that `@Nullable` methods weren't null checked. It happens despite of fact that appropriate null checking helper methods are called right before calling `@Nullable` getter methods.
In earlier versions of InteliJ there was a possibility to add custom null-check methods in the following way:

https://stackoverflow.com/questions/19302211/how-to-tell-idea-studio-that-the-null-check-has-been-done

but unfortunately the "Confgure Assert/Check Methods" button is gone now (at least in Android Studio) and I have no idea how to handle this annoying issue without removing `@Nullable` annotation from getter methods. 
I don't want to remove this annotation because it allowed me to realize that I haven't null-checked a call of actually `@Nullable` method few times. Well, if it happens to me while using my own library it looks like it could be helpful somehow.

@sockeqwe, any updates on this?

**Comment by dimsuz** [comment]
After upgrading to `mosby-3.0.3` I noticed that `getView()` is not marked as `@Nullable` anymore.
This causes kotlin to infer a non nullable `View` as a return type of `getView()`.

Was this change intentional in `3.0.3`?

By reading this issue I figure that it was initially decided to leave `@Nullable` annotations for safety, not to remove them...

In `kotlin` it is easy to do something like

```kotlin
val MvpBasePresenter.viewUnsafe = this.view!!
```

but in Java it's not so nice of course...

**Comment by sockeqwe** [comment]
The change was intentional. I thought, however, that if it is not annotated at all kotlin treats it as nullable.

**Comment by PaulWoitaschek** [comment]
Kotlin does not infer it as non nullable. 

It infers something in between. 

It does not warn you when you use it without checking for null. But it does not say your check is unnecessary either.

**Comment by dimsuz** [comment]
It infers it as platform type by default, which has a behavior you described. But if it sees a nullabilty annotation, it will make use of it and infer either a nullable or non-nullable type depending on whether it was `@Nullable` or `@NonNull`... So it can make a difference.
