### ISSUE TITLE
MvpNullObjectBasePresenter is not needed

### ISSUE THREAD

**Issue by paulirotta** [sockeqwe/mosby#126]
This is a rather complex and confusing version of null object pattern. A good pattern, but in this case the value added is less than the confusion to users of the library.

There is also apparently an error. It should start with 
```java
   @SuppressWarnings("unchecked")
   private final V NULL_VIEW = (V) new Object();
   private V view = NULL_VIEW; 
```

and associated changes, then a lot of complex games go away and the value is never null.

But: you are introducing the same value as your default except a subtly different contract that NullPointerException can be thrown and WeakReference is not used. Probably it is better to help lower cognitive load for users by choosing one way or the other, but not both. The very few users who really want it another way are still free to do that.

**Comment by sockeqwe** [comment]
I think there is a misunderstanding. The intention of this class is to remove all this `isViewAttached()` checks for `MvpBasePresenter` and that you have some kind of safety net in the case you have forgotten to cancel an async background task like this:

```java
class MyPresenter extends MvpNullObjectBasePresenter<MyView> {

  public void loadData(){
          new AsyncTask<Foo>(){

             public Foo doInBackground(){
                   // do something
                   return new Foo();
             }

           public void onPostExecute(Foo result) {
               getView().show(result);
           }
        }.start();
   }
}
```

So the thing here is that we have forgotten to cancel the async task in `Presenter.detachView()`. So image the Task starts, then the user closes the Activity before the Task has completed (so presenter.detachView() will be called and View will be null), and then  the Presenter tries to "deliver" the result in `onPostExecute()`. In `MvpBasePresenter` you would have the `if(isViewAttached())` check in  `onPostExecute()` to prevent to calling `getView().show(result)` because `getView() == null`. 

With `MvpNullObjectBasePresenter` you don't have to check `isViewAttached()`. Rather you safely call `getView().show(result)` even if the "real view" (i.e. activity) is detached, because getView() will not return null. In this case it will return a `MyView` NullObject instance (constructed by reflections) that simply do nothing on invocation of `show(result)`. 

This must be done by reflections an cannot be done with ` private final V NULL_VIEW = (V) new Object();` because otherwise the app will crash because it cannot be casted to `MyView` because obviously an instance of `Object` is not `MyView` when invoking `show(result)`.

However, yes there is a lot of room for improvements:

Memo to myself:
 - Instantiate `NULL_VIEW` only once in constructor and reuse it
 - Check for Generic type order of class declaration (must not be `[0] `)
 - Consider adding `WeakReference` to avoid memory leaks if misused with non custom MvpDelegate that forgets to invoke `presenter.detachView()`.
