### ISSUE TITLE
Handling cached data in Mosby with RxJava

### ISSUE THREAD

**Issue by fdorssers** [sockeqwe/mosby#130]
This isn't as much as an issue as it is a question, but I'm wondering if you have a suggestion on how to handle and show cached data using RxJava in Mosby.

I'll use the `sample-dagger2-rx` module as example. This contains `ReposPresenter` which extends `MvpLceRxPresenter`. This presenter uses `.setData(data)` on the view in `.onNext(data)` and then actually makes this visible in `.onCompleted()` with `.showContent()`. However in this case you would always have to wait for the API call to GitHub to finish. This means that if I've just loaded the repos, closed the app, disabled internet, and loaded the app back up, it would give me the error screen because it can't get any data. However I'd like it to be able to show previously stored data.

So lets wrap this call in a model, interactor, or whatever it's called in MVP:

```Java
public class RepoModel {
	public Observable<Repo> getRepos(boolean useCache) {
		Observable<List<Repo>> api = githubApi.getRepos();
		if (!useCache) {
			return api;
		}
		Observable<List<Repo>> local = githubSql.getRepos();
		return Observable.concat(local, api);
	}
}
```
And use it in the presenter:
```Java
public void loadRepos(boolean pullToRefresh) {
	Observable<List<Repo>> observable = repoModel.getRepos(!pullToRefresh);
	subscribe(observable, pullToRefresh);
}
```

This is just a simple representation, omitting storing of the response, etc. In this case the `.getRepos(useCache)` call on the model gives us an observable which will call `.onNext(data)` twice if we use the cache (if we don't use pull to refresh), once with the local data and once with the api data. But `.onCompleted()` won't be called until the observable is finished, so the first `.onNext(data)` will never be visible. 

So I could solve this by changing `.onNext(data)` and `.onCompleted()` to the following:
```Java
protected void onNext(M data) {
    if (isViewAttached()) {
        getView().setData(data);
        getView().showContent();
    }
}
```
And:
```Java
protected void onCompleted() {
    unsubscribe();
}
```
This way `.onNext(data)` will also show the content in each call and `.onCompleted()` will only unsubscribe. Obviously this still leaves some other small things, like changing `.onError()` to only show a full screen error if we haven't ever cached any data yet, otherwise we can always show the small error (toast, snackbar, whatever), that's also used for a pull to refresh error. 

Anyway, I'm wondering what your take on this is. Maybe you see something I'm missing, or maybe you'd do it in a completely different way within Mosby.

**Comment by sockeqwe** [comment]
The way you are doing it is correct. Mosby doesn't specify anything about RxJava or how to handle subscription callbacks like `onNext()`, `onError()` and `onCompleted()`.

So in your case doing something like 

```java
protected void onNext(M data) {
    if (isViewAttached()) {
        getView().setData(data);
        getView().showContent();
    }
}
```

sounds reasonable if your `onNext()` gets called multiple times.
Actually, that is the reason why there is no build in `MvpLceRxPresenter` in Mosby because I can't provide a presenter class to extend from for all different kind of use cases.

So yes, go ahead and write your own Presenter (or rx subscriber) that fits for your use case.
If you find the interaction between view and presenter too complex than probably LceView is not the right choice for you. Then you should think about writing your own View Interface with those method you exactly need.

Regarding error handling (again it's not Mosby related, it's RxJava related) you might not want to call `onError()` if you an networking or cache error (or not available) occurs. You can use other rx java operators like `onErrorResumeNext()` or `onErrorReturn()` etc. which can be applied on cacheable observable and networking observable to control the overall observable flow in case of errors.
Additionally, if your View needs to distinguish between cache or network `onNext()` you could also think about delivering the result in a wrapper class like this:
```java
class Result {  
  Repo result;
  boolean fromCache;
}
```
and then Presenter subscribes to `Observable<Result>` rather than `Observable<Repo>` (so also your `onNext(Observable<Result>)` contains the info if coming from cache or network).

Also, if you are using retrofit you can override caching headers to force retrofit to always hit the disk cache first (and deliver result in `onNext()` ), and then continue with the real network request which then triggers again `onNext()`.
