### ISSUE TITLE
Odd behaviour between Conductor, Rx and Mosby

### ISSUE THREAD

**Issue by leonardo2204** [sockeqwe/mosby#136]
Hey, I just [posted this question on SO](http://stackoverflow.com/questions/37281700/mosby-conductor-and-rx-not-playing-well) because I'm struggling with screen rotation and navigating away from my first screen.
I explained well on SO, so to not be repetitive I'll keep this issue small.

The project I mentioned on SO is : https://github.com/leonardo2204/ConductorSample

Thanks for the great work !

**Comment by sockeqwe** [comment]
Hi, I will checkout your example in the evening. 

 > or rotate, the problem described starts.
rotation should work, that might be a bug

> navigate away from the FirstScreen or rotate the device, after Rx onNext callback, the `isViewAttached()`
This actually is the correct behaviour as for now, but I might change that in Mosby 3.0  / mosby-conductor 1.0. The problem is that if you Navigate away, the view will be destroyed. If there is no View what should the Presenter update then? So this is more a philosophical question I know. 
My inital thought was,  that if you want to do so Conductors `setRetainViewMode(RETAIN_DETACH)` mode would be an option, but I'm not sure if this will leave to memory issues in big apps.

Therefore I thought, it would be better to go the simple way, if there is no view then Presenter can't do nothing and should unsubscribe from observables in `presenter.detachView(false)`, then once the user comes back to your first screen `presenter. public void subscribe(@NonNull UseCase useCase, @Nullable Bundle bundle, final boolean pullToRefresh)` will be called again.

feedback is very welcome.

**Comment by leonardo2204** [comment]
First of all thanks for the reply !
I'll wait for some news on the 'likely' rotation bug.
As per the Rx issue, the problem is that I'm back on the view that calls the Rx, so in my mind it makes no sense that the isViewAttached() returns null. I guess it will be easier to see the code !

Again thanks for the help and the excellent lib !

**Comment by sockeqwe** [comment]
Is your sample project up to date? I only see a white screen when starting the app ...

**Comment by leonardo2204** [comment]
Sure, no problem.
To reproduce:
First click on the text on the toolbar (the contact list will be updated). The text means to filter contacts with number only, or not.
Rotate the device.
If you click again nothing will happen, because the Rx onNext callback never gets called, since onViewAttached() is false.

**Comment by sockeqwe** [comment]
I found the issue: This is not a Mosby-Conductor problem. this issue has been caused by dagger and the way you inject the presenter. 

You are creating and injecting a new Presenter instance on every screen orientation change in your `onViewBound()` method. That means every screen orientation a new presenter will be created. 

Moreover, since you are declaring your own field for presenter you are not using `MvpLceViewStateController` field for Presenter. See: https://github.com/sockeqwe/mosby-conductor/blob/master/mvp/src/main/java/com/hannesdorfmann/mosby/mvp/conductor/MvpController.java#L19

Mosby internally works as follows:

```java
if (getPresenter() == null) {
     setPresenter(  createPresenter() ); 
}
```

In `MvpController` (the base class of `MvpViewStateLceController` you are extending from `getPresenter()` and `setPresenter()` are using `MvpController.presenter` field. 
https://github.com/sockeqwe/mosby-conductor/blob/master/mvp/src/main/java/com/hannesdorfmann/mosby/mvp/conductor/MvpController.java#L19


There are two solutions:
1. Don't declare your own presenter field but rather do something like this (then it will use  `MvpController.presenter` field):

```java   
 @Override
    public FirstScreenPresenter createPresenter() {
        return DaggerFirstScreenComponent.builder()
            .activityComponent(((RootActivity) getActivity()).getActivityComponent())
            .firstScreenModule(new FirstScreenModule())
            .build().presenter();
    }
```
This ensures that a presenter instance will be created only once since `createPresenter()` will only be called once.

2. If you want to use your own field presenter then you also have to override `setPresenter()` and `getPresenter()` in your controller that extends from MvpLce

```java
public class FirstScreen extends BaseController<RecyclerView, List<Contact>, FirstView, FirstScreenPresenter> implements FirstView {

    private static final String MUST_HAVE_NUMBER = "must_have_number";
    @Inject
    protected FirstScreenPresenter presenter;

   @Override
    public FirstScreenPresenter getPresenter(){
        return presenter;
    }

    @Override
    public void setPresenter(FirstScreenPresenter p){
       this.presenter = p;
    }
```

because of the way Mosby internal works it calls `getPresenter()`, `createPresenter()`  and `setPresenter()`. But still, you have to ensure not to create and inject a new Presenter in your `onViewBound()` method.




Btw. you will run into  same "problem" if you use Mosby with Activity / Fragments

**Comment by leonardo2204** [comment]
First of all, I really appreciate all your explanation and help, I'll dive deeper into your code to learn more.
I think I solved the problem by creating a onCreate method as seen on [Conductor #34](https://github.com/bluelinelabs/Conductor/issues/34):

```
@NonNull
    @Override
    protected View onCreateView(@NonNull LayoutInflater inflater, @NonNull ViewGroup container) {

        if(!created){
            onCreate();
            created = true;
        }

        View v;
        v = inflateView(inflater, container);
        ButterKnife.bind(this, v);
        onViewBound(v);

        return v;
    }
```
And use like this:
```
@Override
    protected void onCreate() {
        DaggerFirstScreenComponent.builder()
                .activityComponent(((RootActivity) getActivity()).getActivityComponent())
                .firstScreenModule(new FirstScreenModule())
                .build().inject(this);
    }
```
I tested and it works. So, is that a good solution ? Should I save the created variable on saveInstance ?
Thank you so much again !

**Comment by sockeqwe** [comment]
You are welcome. No you don't have to save that in onSaveInstanceState() ...
For now forget everything I mentioned before about
onViewStateInstanceRestored() ... you only run into this if you use hot
observables like sqlbrite, then you have to write 2-3 lines of code to
solve that manually, but for now it seems like you were using rxjava as
async task replacement and in that case everything should work out of the
box...

Leonardo Ferrari <notifications@github.com> schrieb am So., 22. Mai 2016,
19:07:
