### ISSUE TITLE
Architecture question

### ISSUE THREAD

**Issue by PingForward** [sockeqwe/mosby#141]
I'm a little bit confused. 
As I understand in the MVP all logic should be placed in the presenter. But how I can achieve this using library like FragmentArgs which inject objects to my View
```
@FragmentWithArgs
public class OfficeDetailsFragment extends BaseFragment {

    @Arg
    Office office;

    @Inject
    Retrofit retrofit

    BasePresenter presenter;
....
}
```
For example this `OfficeDetailsFragment`. I pass prcelable office object from my list to fragment and when I inject fragment args I have instance of Office in my View. About retrofit object in View with dagger2 it can be done by using constructor injection in presenter and in a View I just inject the presenter.

What do you think about storing model object in the View?

**Comment by dimsuz** [comment]
What I do is right after I created a presenter in `createPresenter()`, I extract a model object from Intent/Args and user `presenter.setModel(model)` before returning it.

And this is the only part where view sees this model object. It only cares to extract it and pass to the presenter - and it's done with it.

**Comment by PingForward** [comment]
@dimsuz yes, I agree with you it is a good solution I used it in the previous project. Then I try FragmentWithArgs it is pretty cool lib but I think using it with MVP architecture is a bad idea.

**Comment by dimsuz** [comment]
Oh, I didn't understand that you are talking about  a custom library.

**Comment by PingForward** [comment]
@dimsuz I talk about architecture but seems  [this](https://github.com/sockeqwe/fragmentargs) library broke MVP logic and I think some one know good hack to leave the lib and use MVP to the right way.

**Comment by sockeqwe** [comment]
I don't think that this is a problem of Mosby nor of FragmentArgs. As long as you treat the passed `Office` just an an argument and not as the actual model in your view everything is fine in my opinion.
What's the difference between passing an id (let's say an integer) or a concrete object (as in your case a `Office` object as argument? Or Activities Intent extra? Treat them just as arguments.

If you just going to display `Office` details, then you may don't even need MVP at all, but just display that `Office` in your UI directly.

Otherwise, I tend to agree with @dimsuz . Either create a Presenter with your office object as constructor parameter or for example if you are going to load some data for the given `office` object pass the office object as parameter to the corresponding presenter method like this: `presenter.load(office)`.

Btw. since this is an issue tracker, I would like to suggest to ask this kind of questions on stackoverflow. Mainly because stackoverflow is quite good indexed by google so it is easier for others facing the same problem to find the answer there. It's really hard to find questions / answers on Github's issue tracker system, especially when the issue has been closed.
