### ISSUE TITLE
Provide MvpSupportMapFragment

### ISSUE THREAD

**Issue by vanniktech** [sockeqwe/mosby#143]
Could be in a separate module, maybe called components. Would basically be a copy of `MvpFragment` with the slight change of `extends Fragment` to `extends SupportMapFragment`.

Let me know what you think of this.

**Comment by sockeqwe** [comment]
Would rather prefer not to add third party libraries because that would
mean to update and release a new version of Mosby every time MapFragment
will be updated. But I'm open to discuss that.

Alternatively, if you want to build a library just for MapFragment support
by your own, I will be more than happy to add a link to your library.

Niklas Baudy <notifications@github.com> schrieb am Di., 12. Juli 2016,
15:05:

**Comment by vanniktech** [comment]
Alright I'll prep something up and let you know.

**Comment by lurbas** [comment]
@vanniktech You can also use MapView inside your MvpFragment. Maybe that would be easier for you.

**Comment by sockeqwe** [comment]
I'm closing this for now, but I'm open to reopen and continue the discussion ...
