### ISSUE TITLE
Could you explain why are you using onViewCreated() life-cycle callback for injectDependencies() and ButterKnife.inject(this, view)?

### ISSUE THREAD

**Issue by ar-g** [sockeqwe/mosby#146]

**Comment by sockeqwe** [comment]
Mostly because I use retaining Fragments.
Therefore, `Fragment.onCreate()` is only called the very first time. If for example you do dependency injection in `Fragment.onCreate()` and for instance access `Fragement.getActivity()` in your dagger module, you will run into memory leaks after screen orientation changes, because the injected components still may reference to the "old" activity (before screen orientation changes) and no new ones will be injected as `Fragment.onCreate()` will not be called again after screen orientation changes for retaining Fragments.

So one could discuss why not  doing all that in `Fragment.onCreateView()` ? Well, this is just a personal preference. You could also do it there, but `Fragment.onViewCreated()` feels more obvious to me and just inflate the xml layout in `Fragment.onCreateView()`. Again, that is just a personal preference...

**Comment by ar-g** [comment]
Makes sense for me now. Thanks!
