### ISSUE TITLE
Suggested proguard configs ?

### ISSUE THREAD

**Issue by javajack** [sockeqwe/mosby#15]
I have already used Mosby to make one app live.

https://play.google.com/store/apps/details?id=com.timesbuzz.news

Unfortunately I am a naive Android Developer and made classic mistake.
The released apk doesn't work. I have messed up the proguard config.

Most of the heavy lifing is done by Mosby ( and its components like dagger1, retrofit, fragmentargs,Icepick etc)

So what is the most appropriate proguard config for any project which leverages the mosby ?

It's a kind of blocker issue and I humbly request if it is possible to provide the proguard config for mosby and it's components based project.

**Comment by sockeqwe** [comment]
mosby itself needs no special proguard rules.
However, third party libraries like Butterknife, Icepick, FragmentArgs, Retrofit  and Dagger need have proguard rules you have to add to your project.

I have add that to the README.  Im sorry about that.

It's possible now to ship android libraries with proguard files. But I'm not sure if this will cause any further problems since the user of mosby can update to any other version of the used libraries ... I have to check the documentation.
