### ISSUE TITLE
What is the best practice for passing fragment's arguments to presenter?

### ISSUE THREAD

**Issue by sergio11** [sockeqwe/mosby#157]
I have the following code:

```
public class DeviceDetailFragment extends BaseViewStateFragment<IDeviceDetailView, DeviceDetailPresenter> implements IDeviceDetailView {

    private static final String ARG_DEVICE = "device";


    private DeviceDetailComponent deviceDetailComponent;
    private Device device;

    public DeviceDetailFragment() {}


    public static DeviceDetailFragment newInstance(Device device) {
        DeviceDetailFragment fragment = new DeviceDetailFragment();
        Bundle args = new Bundle();
        args.putParcelable(ARG_DEVICE, device);
        fragment.setArguments(args);
        return fragment;
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (getArguments() != null) {
            device = getArguments().getParcelable(ARG_DEVICE);
        }
        setRetainInstance(true);
    }

    @Override
    public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
        injectDependencies();
        super.onViewCreated(view, savedInstanceState);
        ButterKnife.bind(this, view);
    }

    @Override
    public void onDestroyView() {
        super.onDestroyView();
        ButterKnife.unbind(this);
    }

    @Override
    protected int getLayoutRes() {
        return R.layout.fragment_device_detail;
    }

    @Override
    public DeviceDetailPresenter createPresenter() {
        return deviceDetailComponent.DeviceDetailPresenter();
    }

    @Override
    public ViewState createViewState() {
        return new DeviceDetailViewState();
    }

    @Override
    public void onNewViewStateInstance() {
        presenter.init();
    }


    protected void injectDependencies() {
        deviceDetailComponent = BaseApplication.get(getContext()).getUserComponent().deviceDetailComponent();
        deviceDetailComponent.inject(this);
    }

    @Override
    public void showDeviceDetail(Device device) {
        
    }
}
```

I want to know what is the best way to spend the device argument to presenter (MvpViewStateFragment)

**Comment by sockeqwe** [comment]
There are 3 options:

1. Don't use Fragment Arguments, but rather let the Presenter "query" the desired data object (Device) from underlying business layer. But it seems that this is not a suitable case for you.
2. Pass the Fragment Argument as constructor parameter like `new DeviceDetailsPresenter(device)`. Since you are using dagger, you don't want to instantiate a `DeviceDetailsPresenter` directly, right? To "fix" that you have to you have to create scoped component / subcomponent for this "DeviceDetailsScreen". I would suggest to create something like a `DeviceDetailsScreenModule` which provides a `Device`:

```java
@Module
class DeviceDetailsScreenModule {
    private Device device;
    public DeviceDetailsScreenModule(Device device) { this.device = device; }

   @Provides public Device proviceDevice(){ return device; }
```

```java
public class DeviceDetailsPresenter extends MvpBasePresenter<DeviceDetailsView> {
       @Inject public DeviceDetailsPresenter(Device device) { ... }
}
```

3. Pass the fragment argument as presenter's method parameter. I usually do this for "Screens" that have some id's as Fragment Argument like imagine a News Application where you have a Fragment to read a NewsArticle. Then my `NewsArticlePresenter` would have some method like `presenter.loadArticle(articleId)` (where article id was the fragment argument). Not sure if this works in your case (`presenter.init(device)`? but in that case I would definitely prefer to pass that as construcor parameter, so solution 2. seems to be better suited solution).


There is no silver bullet, but I usually choose one of this 3 solutions (mabye there are better ways of which I'm not aware of). Usually number `1.` and `3.` fits my needs.

Also worthwhile mentioning: If you just display static data, you may not need MVP at all. Just show it directly in your Fragment.
