### ISSUE TITLE
Presenter doesn't attach view after returning to the activity.

### ISSUE THREAD

**Issue by DasCody** [sockeqwe/mosby#161]
Hey I ran into a bit of an edge case with this library where I load activity A, advance to activity B, load a new instance of activity A, go back to activity B, and then go back to activity A. Now when I try to interact with activity A the view is no longer attached to the presenter. Looking at ActivityMvpDelegateImpl.java it looks like the view is attached in the onCreate, I was wondering if it'd make more sense to attach the view in onResume?

Currently my fix for this is to call `getPresenter.attachView(...)` in the onResume method of my activity and that resolves the issue.

**Comment by sockeqwe** [comment]
Sounds like a both instances of Activity A share the same presenter instance. Are you returning the same presenter instance in `createPresenter()`? Are you using Dagger2? Sounds  like you have scoped singleton of the presenter. Please verify that.

You can be sure that Mosby is not sharing the same presenter instance just because the view is of the same type. Every View gets his own Presenter by calling `createPresenter()`, but if you return the same Presenter instance from `createPresenter()` both views (both instances of Activity A) will share the same presenter instance causing this issue described by you.

**Comment by DasCody** [comment]
Yup that's exactly what the problem was. We were using a custom presenter cache that was a little wonky and this afternoon discovered Mosby supports caching the presenter now. We implemented that, I just removed my "fix" and everything still works as I would expect. Thanks for explaining what was going on behind the scenes.
