### ISSUE TITLE
Retaining presenter: Why not using loader?

### ISSUE THREAD

**Issue by Rainer-Lang** [sockeqwe/mosby#162]
I read a lot about how to retain presenters and I'm even a bit confused which method is preferred: Retain fragment, hold presenter in map/array, loaders,.....

**Comment by sockeqwe** [comment]
One could use loaders, but historically they were a little bit more buggy than fragments (this seems to be fixed in latest support library) and I also think that the loaders API is not perfectly designed for such a use case (handling presenters).

Using a map / array is also a possible way, but then you have to assign id's to map views to presenter. Also you have to manage lifecylce events i.e. when do you remove a presenter from a map? Definitely solvable problems, but I think its easier to implement by saying the presenter sticks as long as the view object is not garbage collected.

Therefore, I, personally, prefer Retaining fragments.
