### ISSUE TITLE
Why isViewAttached()?

### ISSUE THREAD

**Issue by lyrachord** [sockeqwe/mosby#167]
Hi, I'm reading Mosby document before divide into the code.
There is a question: 
Why isViewAttached()? 
IMHO, Presenters provide serivce for views or control views, all the (view) operations are tight relative to views in kernel, so the core of these operations is that there must be a view. So why isViewAttached()?

Thanks

**Comment by lyrachord** [comment]
In FAQ, I saw an answer for the question. But it seems not a perfect choice for me.
To me, If AsyncTask need, the callback listener should be responsible for the view existing checking.
So there are some other considerations for isViewAttatched()?

**Comment by Try4W** [comment]
I trying to avoid using `isViewAttatched` as it hides unexpected behaviour when some callbacks can be executed when view is detached without any `Exception`. So, I just drop all requests to model in `detachView` method.

**Comment by lyrachord** [comment]
Thanks @Try4W looks the dropping is one of best practice.
The key is still how and where and who to manage the existing state?

BTW I started in code, the interface binding(include superclass binding) seems not so, eh, flexible or agile? Some ways to avoid theses bindings applied well, f.e. eclipse e4.
Any?

**Comment by sockeqwe** [comment]
> For an AsyncTask, the callback listener should be responsible for the view existing checking.
So there are some other considerations for isViewAttatched()?

Typically the presenter is the callback listener. If you forget to cancel a async task, you may run into the situation where the View is not attached, but you try to update the view.

If you are sure that you are handling async operations properly then you dont need the chec `isViewAttached()`. Otherwise,  `isViewAttached()` is kind of a safety net.
Also, there might be situations where you explicitly don't want to cancel a async started operation. This could be handled in your business logic or if updating the view depends on that async operation in presenter i.e. by using `isViewAttached()` check
