### ISSUE TITLE
[Feature] SE View Only

### ISSUE THREAD

**Issue by leonardo2204** [sockeqwe/mosby#168]
What do you think about having a SE(send-error) View/Presenter only ?
That would be useful on Form Scenarios, like logging in, saving data etc.

I'm already implementing it on my app, if you think that would be cool, I can drop a PR !

**Comment by sockeqwe** [comment]
Hi,
well I also caught myself implementing this multiple times, but I would like to avoid putting this into this library, for various reasons:

1. maintaining & testing
2. you never catch all use cases and users will start to complain about it. See #132 #107 #42 about LCE components
3. I would prefer to keep this library small and concise. See #143  about adding support for Map Fragments. The problem is if we add SE, then next month we may have to add another XY component too and so on.

I'm open to discuss that, but I think it would be a better approach to write and publish a standalone SE library on top of Mosby. I would be more than happy to share the link to such a extension module library in the README. See https://github.com/Bodo1981/appkit


What do you think?

By the way: In my experience you need 3 states i.e. for login: 1. Show login input form. 2. Show loading (Sending) 3. Show Error ( and optionally 4. Show successful)

**Comment by leonardo2204** [comment]
Sure, no problem.
I see your point and I agree that people may complain about some tweaks it should have or use cases it wouldn't cover. Nevertheless I think it's a very common use case, and I also get myself implementing this over and over. I'm not sure if it's a good approach to create a lib on top of that just for this feature. If so, LCE should also be a part lib, right ?

About the states, I agree 100%, that' how I do on my side. And I'd give a +1 for the step 4, show successful callback.

Thanks for taking your time and I really appreciate all the work and effort you put on your project dude !

**Comment by leonardo2204** [comment]
Hey @sockeqwe, how is it going ?
I came up with something like that https://github.com/leonardo2204/mosby/commit/e44e19ff6493576d1142f98aa0f9d0267d31882c

See what your toughts are on that !

**Comment by sockeqwe** [comment]
Sorry, I am a little bit busy right now, I will take a detailed look during the weekend...

Indeed, there are discussions going on to remove LCE from this project (or at least package it into is own artifacts) #148 and I think if I would rewrite this project from scratch I wouldn't add LCE into this project. 

Usually, some other Mosby users give their feedback here on github on some project related decisions. I think we should wait some more days, maybe we get some more opinions about that, and then we make a final decision. I'm open to discuss that with the community and you are part of the community!

> I'm not sure if it's a good approach to create a lib on top of Mosby

I'm not really talking about writing a whole big library like appkit, I'm just saying that instead of putting all you code into Mosby directly, we could simple publish those classes as its own artifact (with having a dependency to Mosby).


Does that all makes sense for you?

**Comment by leonardo2204** [comment]
Sure, no problem !
Ohh I see it, so that would be something like the viewstate separate lib, right ? I misunderstood haha. In that case I think that would be just fine, also we could even extract the LCE part into the same package.. What do you think ? 
We'd have something like a MosbyForm, something like that (I'm not good at naming things).

Thanks for your time, I'll wait for some other feedback ;)

**Comment by dimsuz** [comment]
We are using mosby in several projects and in each of them we have different requirements for LCE views which happen to differ a bit from each other. And also from Mosby's default implementation of LCE. The concept is there, but I discovered that it is sometimes easier to create my own implementation of LCE stuff than to try to customize mosby's and to apply workarounds for functionality it does a little bit differently. For example mosby has the concept of `pullToRefresh` (last time I looked) while I might not need it, etc etc.

So I feel that it would be a correct move - to separate this into a different artifact which would provide this functionality for the projects that can use it right away. And other implementations can use that for a reference and inspiration also :)

**Comment by DrewCarlson** [comment]
I also use multiple variations of LCE for different cases and some are the Mosby provided implementation.  To the same end I have two implementations around forms as well.

I'm onboard with moving LCE and adding other things like SE to a separate module, that makes the most sense to me.

**Comment by leonardo2204** [comment]
I kinda stopped developing this features waiting for a feedback from you guys...
Any thoughts on how to design this new features ?

**Comment by sockeqwe** [comment]
I think we can add this but in a separate module in Mosby 3.0 . Still not sure about the naming...

**Comment by leonardo2204** [comment]
@sockeqwe Thanks for the feedback !
Sure, do you have any naming sugestion ? 
As soon as I have some more time, I'll keep implementing !

**Comment by sockeqwe** [comment]
Regarding naming: Content Loading Error Success  (CLES) ? Doesn't sound that nice in my ears but nothing better came into my mind until now ... not sure ...

**Comment by leonardo2204** [comment]
@sockeqwe Hmm, I'm not sure about that, IMO, it doesn't seem like a "natural" name to refer to Form views. Maybe using send or something else to make it clearer ? Something like Send Loading Error Success (SLER) or Form Loading Error Success (FLES) ??
