### ISSUE TITLE
[Question] Replace presenter for Testing.

### ISSUE THREAD

**Issue by kevinlg** [sockeqwe/mosby#181]
I would like to write test to a project using expresso. I am wondering if there is an easy way to replace the presenter by a mock in order to test the activity without having to hit real server. 

I have tried to set the mock presenter in the setup method but the presenter from the createPresenter of the activity being test is still being used. 

Has anybody run into the same issue ? What would be the approach you recommend to be able to replace the activity presenter ? 

Thanks for the help.

**Comment by sockeqwe** [comment]
hello,
well if you want to use a "MockPresenter", then you `createPresenter()` method must return such a `MockPresenter` during testing and your `RealPresenter` in production.

So the question is how to change the return value of `createPresenter()`? If your code looks like this:

```java
class MyFooActivity extends MvpActivity {

   ...
   public FooPresenter createPresenter(){
        return new FooPresenter();
   }
}
```
then you were not able to "dynamically (at runtime, at the time `createPresenter()` is executed)" return another `MockFooPresenter` because you have hardcoded `return new FooPresenter()`.

Typically Dependency Injection libraries like Dagger are used to solve this kind of problem.

With Dagger2 your code may look like this:

```java
class MyFooActivity extends MvpActivity {

   ...
   public FooPresenter createPresenter(){
        return DaggerFooComponent.create().getFooPresenter();
   }
}
```

While testing Dagger will return a Mock Presenter in `getFooPresenter()` whereas in production it returns the real foo presenter.


So in general: You can't hardcode `new FooPresenter()` but you have to find a way to "dynamically" instantiate a presenter. Something like this would work:

```java
class MyFooActivity extends MvpActivity {

   ...
   public FooPresenter createPresenter(){
        return ((FooApplication) getApplication()).getPresenterFactory().getFooPresenter();
   }
}
```

and then during unit test you have to create and use `FooTestApplication extends FooApplication` which overrides `getPresenterFactory()` to return a factory that then eventually returns `MockFooPresenter` when calling `getFooPresenter()`. Last you have to ensure that `FooTestApplication` is used during testing instead of the "real" `FooApplication`. This is done with a custom JUnit Test Runner or JUnit rule.

If you are already familiar with dagger, then maybe you are wondering how you can provide a `MockFooPresenter`. In that case I strongly recommend to take a look at Artem Zinnatullins awesome sample project: https://github.com/artem-zinnatullin/qualitymatters
The trick is that the "main" dagger component is composed in `QualityMattersApp extends android.app.Application` and during testing another instance `QualityMattersIntegrationTestApp extends QulityMattersApp` is used (custom test runner or junit rule) which then composes the dagger component with the mock components:
https://github.com/artem-zinnatullin/qualitymatters/blob/master/app/src/integrationTests/java/com/artemzin/qualitymatters/QualityMattersIntegrationTestApp.java#L23


Another thing to note is that, if you just don't want to hit the real server, then you should consider mocking the http connection with the server or use a mock web server (instead of mocking the Presenter). okhttp offers a `MockWebServer` and Artem Zinnatullin also has a great example for that: https://github.com/artem-zinnatullin/qualitymatters/blob/master/app/src/integrationTests/java/com/artemzin/qualitymatters/integration_tests/api/QualityMattersRestApiIntegrationTest.java#L33

Happy testing!
