### ISSUE TITLE
@Scope usage

### ISSUE THREAD

**Issue by IgorGanapolsky** [sockeqwe/mosby#19]
Hi,
why don't you use @Scope from `javax.inject.Scope` in your project.  I thought Dagger2 implementations should have things like **@ApplicationScope** or **@ActivityScope**.

Thanks,
Igor

**Comment by sockeqwe** [comment]
Im not sure what you are talking about. Are you just talking about the dependency declaration:
`compile 'javax.annotation:javax.annotation-api:1.2'`

or why im using `@Singleton` instead of defining things like `@ActivityScope`?

Regarding the second one: I'm just lazy :)


Btw. The mail sample will get a huge dagger2 update.

**Comment by IgorGanapolsky** [comment]
What I am talking about is what Jake Wharton used in his u2020 project for Dagger.  You can also see usages of this for Dagger 2 here: https://github.com/LiveTyping/u2020-mvp

**Comment by IgorGanapolsky** [comment]
Does `@Singleton` replace `@ActivityScope`?

**Comment by sockeqwe** [comment]
https://github.com/LiveTyping/u2020-mvp/blob/master/app/src/main/java/ru/ltst/u2020mvp/ui/ApplicationScope.java

`@Singleton` is just an `@Scope` like `@ActivityScope`  or `@ActivityScope` is. 
You could say that `@Singleton extends Scope`  and  `@ActivityScope extends Scope` ...

`@ActivityScope` is defined in the u2020 project, it's nothing already provided by dagger2, while `@Singleton` is officially part of `javax.inject` package.

**Comment by IgorGanapolsky** [comment]
I see.  I guess I'll stick to your simpler implementations :)
