### ISSUE TITLE
Cannot find `MvpView` or `MvpPresenter`

### ISSUE THREAD

**Issue by manabreak** [sockeqwe/mosby#208]
I'm using Mosby 3 snapshot, and this issue has been going on for a while. It seems that randomly during Gradle sync some (or all) Mosby classes are not found. This usually can be solved by manually removing the Mosby files from ~/.gradle and resyncing. However, now these two interfaces won't restore themselves. Because of this, my project won't build anymore.

Is there something wonky going on with the snapshots? This has never happened with any of my other dependencies, or with Mosby 2.

**Comment by sockeqwe** [comment]
Really strange,
I never seen or heard of such a behavior before.

You could try to use `alpha4` rather than snapshot. Does that solve your
issue?
manabreak <notifications@github.com> schrieb am Mi., 8. Feb. 2017, 08:17:

I'm using Mosby 3 snapshot, and this issue has been going on for a while.
It seems that randomly during Gradle sync some (or all) Mosby classes are
not found. This usually can be solved by manually removing the Mosby files
from ~/.gradle and resyncing. However, now these two interfaces won't
restore themselves. Because of this, my project won't build anymore.

Is there something wonky going on with the snapshots? This has never
happened with any of my other dependencies, or with Mosby 2.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sockeqwe/mosby/issues/208>, or mute the thread

**Comment by manabreak** [comment]
The `alpha4` seems to solve the issue. It's really weird that the `SNAPSHOT` doesn't seem to have the interfaces.

**Comment by sockeqwe** [comment]
I apologize, i will manually upload a new snapshot

manabreak <notifications@github.com> schrieb am Mi., 8. Feb. 2017, 08:32:

**Comment by manabreak** [comment]
No problem, and thanks for quick support. :)

**Comment by sockeqwe** [comment]
I have redeployed the SNAPSHOTS. If you have 2 minutes, could you please check and verify if that this solves your reported issue?

**Comment by manabreak** [comment]
Doesn't seem to work. with `alpha4` the interfaces are there, with `SNAPSHOT` they're not. Odd.

**Comment by sockeqwe** [comment]
I have no clue what happened and I can't reproduce it. I close the is issue for now. If you have any problem in the future please reopen this issue
