### ISSUE TITLE
MvpViewStateFragment<MvpPresenter> vs MvpViewStateFragment<MvpView, MvpPresenter>?

### ISSUE THREAD

**Issue by GNima** [sockeqwe/mosby#28]
In the samples and your blog post I see you used a version of `MvpViewStateFragment` that takes a View and Presenter, but in the library v1.0.0 it only takes a presenter. Am I doing something wrong?

**Comment by sockeqwe** [comment]
You are right, in my blog post I'm talking about `v 1.0.0`  with`MvpViewStateFragment<MvpPresenter>` (I will update this blogpost as soon as I have release `1.1.0`).  If you have cloned the current master branch then you will see `MvpViewStateFragment<MvpView, MvpPresenter>` since I'm working on `1.1.0` and I had made this change to implement a more type safe way to deal with internal delegates #14 

If you want to play around with mosby the current master branch or the latest snapshot is completely fine (version 1.1.0). You can expect that msoby 1.1.0 is going to be realeased very soon.
