### ISSUE TITLE
Question about repository pattern in MVI

### ISSUE THREAD

**Issue by diogojg** [sockeqwe/mosby#306]
Hi, as the title mention I would like to hear your opinion about how do you approach the repository pattern in MVI. This is actually kind of a silly question since this pattern should behave the same way regarding which architectural pattern it's used on the project.

So my question is, when you have an interface like ProductRepository, with a method like 
`fun getProductDetail(id: Int): Observable<ProductDetails>`
do you treat this method like a Single (in RxJava) or you expect the implementation to return updates every time there is a change in "ProductDetails"?
My question comes at the point that we dont know about the implementation of this repository interface (so it could be just a simple REST call or it could be like a web socket implementation). 

If the business logic "knows" that these are just singles REST HTTP calls, should the repository interface be based on Singles or Observables?

I could use a little help to clear out this concepts. What is your way of thinking when you are programming your apps with MVI?

Thank you

**Comment by sockeqwe** [comment]
It depends, but I think your `Repository` could return an `Observable<State>` where State means Error, Loading, Result (List<ProductDetails>) and so on.

so rather than `fun Repository.getProductDetail(id: Int): Observable<ProductDetails> ` I would implement `fun  Repository.getProductDetail(id: Int): Observable<State>`
