### ISSUE TITLE
RetainingFragmentLceViewState and fragment recreation

### ISSUE THREAD

**Issue by legarspol** [sockeqwe/mosby#38]
Hi !
I've been using your RetainingFragmentLceViewState and it works great on device rotation.
But I have a problem when the fragment is recreating because of low ram or long stay in background:

 - Turn on "Don't keep activities" in developer options
 - create a 2 activity app, the first one having a fragment using a RetainingFragmentLceViewState.
 - start activity 1, from there start the activity 2.
 - press the back button, the activity one is getting recreated, the view state also and it don't care about its previous state. However, everything which is saved without using the view state (views, Icicle) are getting saved and reapplied in the view.

I'm using the 1.1 version of your mvp framework

**Comment by sockeqwe** [comment]
Hi, 
yes this is the "desired" behaviour. 

RetainingFragments (at least in Mosby) can not survive recreation: as you have already noticed correctly viewstate and presenter gets recreated. However, everything else you put into a bundle like `Icicile` gets restored because it has been stored persistently into the Bundle.

Your problem is that you have mixed up two concepts:

EITHER

- put everything into the bundle by not using "RetainingFragment" (so the viewstate will be saved into the bundle as well, but presenter will canceled and restart requests after orientation change) 

OR

- if you use retaining fragment there is no need to use `Icicle`. Simply use fields directly as the will survive orientation changes. By doing so this fields will "loose" their value on activity recreation as well as ViewState and Presenter. So after activity recreation you are in the same "new" state for all components (all fields are reseted and presenter and viewstate as well).

**Comment by legarspol** [comment]
Problem is that in the second case, if the fragment, viewstate and presenter are recreated and empty of past values, the views are still recreated by the system with their previous state...

Then is the cleanest way to deal with it to call a cleaner function to set the initial state of each component ?

**Comment by sockeqwe** [comment]
In that case your viewstate is null and therefore the presenter starts to reload. In that case the loading view gets display, then the contentview with the loaded value.

So yes, the android widgets have restored there previous value, but they are not visible, right? Or probably LCEFragment is not the right thing for your needs? 
 
Could you post some code? Then I should be able to give you a concrete advice?

Usually a clean up method is not neede, because you should set the android ui widgets in `showLoading()`, `showContent()` and `showError()`. However, if you really think a clean up method is needed, then you should override `onNewViewStateInstance()` which is called if no viewstate to restore has been found.

**Comment by legarspol** [comment]
Basically I have a common lce list.
Under this list I have a panel where I have some filters controls (like some 3 states buttons, and spinner)

When the activity is recreated, the fragment and presenter restart but the filters controls keep their previous selection.
The problem is that the data loaded at initialization don't pay attention of the selected controls.

**Comment by sockeqwe** [comment]
I see. That sounds like the filter controls should be part of the view state as well. I guess you filter the list by reloading data in background matching the filter criteria, don't you? If doing so you can enhance an existing LCE viewstate. 

have a look here: 
http://hannesdorfmann.com/android/mosby-playbook/  

Tip 15 and Tip 17 describes how to make a custom viewstate. However, you still have to reset the filer control to it's initial state in `onNewViewStateInstance()`.
