### ISSUE TITLE
Prevent NPE on getView

### ISSUE THREAD

**Issue by dalewking** [sockeqwe/mosby#43]
If you call  getView on MvpBasePresenter and the view is not attached you get a NPE. To prevent that you have isViewAttached. But this is a bad design. There is a potential race condition where if the view got detached between the 2 calls you would get a NPE.

You should change getView to:

    protected V getView() {
         return viewRef == null ? null : viewRef.get();
    }

isViewAttached can then be implemented simply as getView() != null, but it might be better to deprecate in favor of this idiom:

    MyView v = getView();
    if(v != null)
    {
        v,doSomething();
     }

which will not throw an NPE even if the view gets detached since your local variable is a strong reference to the view.

**Comment by dalewking** [comment]
Another question is whether there is a good reason to create and destroy the weak reference or should you just create the weak Reference once when  the presenter Is created?

**Comment by sockeqwe** [comment]
Hi, jep I agree, `getView()` should be implemented this way. I have added that.
However, I don't see any reason for deprecating `isViewAttached()`. 

Presenter can survive orientation changes (i.e. by using retaining fragment) and therefore `attachView()` and `detachView()` can be called multiple times. Since `WeakReference` is immutable there is no other way to reattach a view to an already existing presenter. Btw. you could also write your own BasePresenter without weakreference. `MvpBasePresenter` uses `WeakReference just to avoid memory leaks for the edge case where a developer implements it's own Activity/Fragment and forgets to detach the view from presenter in `Activity.onDestroy()`

**Comment by dimsuz** [comment]
> WeakReference just to avoid memory leaks for the edge case where a developer implements it's own Activity/Fragment and forgets to detach the view from presenter

Hi @sockeqwe! Having seen you repeat this in a few issues, I beleive I am not the only one who was interested in more detailed explanation of the reason you choose to use WeakReference here, so I would suggest to put it either to javadoc or to some documentation/tutorial on the website...

Along with suggestion to the user to implement his on "righteous" base presenter if he wishes to avoid repeating null checks :)
