### ISSUE TITLE
ViewState access from Presenter 

### ISSUE THREAD

**Issue by lurbas** [sockeqwe/mosby#48]
Hi, great library. I'm familiar with this pattern and I'm glad to see a good library and community around it. But I can see an serious issue, or I'm missing something. ViewState is created by View and only View has access to it. In your samples Presenter call method on View and it changes itself and sets proper State. 
Lets imagine that Presenter is doing some background job. After finishing want to call View and change it's State. But screen rotation is happening in the same moment. So when Presenter want to update View between onDetach() and onAttach() this State is lost forever. Maybe it would be better to store ViewState in Presenter? It's not destroyed if fragment has retain flag on. Only problem is when Activity is killed by system in case of memory shortage. Maybe we can save Presenter with ViewState in Bundle to survive recreation by low memory clean up?

**Comment by sockeqwe** [comment]
Oh yeah I thought about this kind of questions and scenarios quite often. Should the Presenter hold the state? is a view state necessary? Let me explain why the "default" implementation does not need a state on presenter site:

> when Presenter want to update View between onDetach() and onAttach() this State is lost forever

I assume that every interaction with the view runs on androids main UI Thread. Since screen orientation changes run on the UI Thread as well it's impossible that you run into the scenarios where your presenter calls a view method between `onDetach()` and `onAttach()`.

>  Maybe it would be better to store ViewState in Presenter?

It's a good question. The point is how and what exactly would you store in the presenter? i.e. Making a simple http request to get a list of items from backend. You may have to store those things into presenter bundle:
- the view's state (like showingLoading(), showingContent(), etc.)
- the loaded data,
- if a request is already running 
- the URL parameters for the requests URL like `http://facebook.com/user/123/friends`, where 123 is the user id and a parameter retrieved from activity intents. The url itself is just a string. But what if its an SQL query. Saving the query as String? Saving all parameters from calling method like `presenter.loadUserFromDatabase(int age, String name, double latitude, double longitude` separately?
- Since the view (Activity or Fragment) is the entry point, how do you easily distinguish between trigger `presenter.loadData()` from view (i.e. when the Activity or Fragment gets instantiated the first time) and letting the presenter restore and re-execute the request by itself.

Well, everything from the list above could be implemented somehow. Some things are easier, some more challenging, some require the end user of this library to write more code (i.e. saving all those parameters for the sql query). 

So I came to the conclusion that a lot of those things are already handled by android itself. Like:

-  if you have an activity, that should get a list of items from backend like `http://facebook.com/user/123/friends` the Intent already has stored the `userid = 123`. 
-  Furthermore, we can rely on that every request is triggered by the view by calling `presenter.loadFriends(getIntent().getIntExtra('userId'));` which reduces the complexity of "should the view call `presenter.loadFriends()` or does the presenter internally restores itself and restarts the requests somehow.

I agree that in a traditional MVP pattern the presenter would be the centralized component and it should be the presenter that stores the state. But from my point of view it makes life and things much easier if the View stores it's state because in that case you only have to take care about two things:

- if there is not state (which means starting the view for the first time or after activity recreation) then call `presenter.loadFriends()`
- if there is a state simply restore it by calling the methods defined in View interface.

The reason why Mosby is implemented this way is **simplicity**  (KISS principle). Always the same workflow - Parameters are stored in Activities Intent or Fragments Arguments.

> Maybe we can save Presenter with ViewState in Bundle to survive recreation by low memory clean up?

As long as you don't use Retaining Fragment the ViewState survives. So if you have loaded the list of Friends the data will still be there after activity recreation. However, you are right that the presenter does not survive. So if the acitivity gets destroyed while a request is running (not completed yet) then Mosby creates a new presenter instance on activity restart and the same request will be started again. I don't think that this makes any difference if you would save the presenters into bundle: at the end you also have to restart the request somehow again, but now you have to consider presenters internal state as well. As already discussed above, from my point of view it's simpler if the workflow is always the same (started by the View, since View is the "entrypoint" on android). I also think that if the android operating system decides that a process should be killed then android has a good reason for doing so and I will not "fight" against that by trying by hard to make the presenter survive or store things somehow. I believe that in that case a "reset" and "restart" is a more friendly option.


However, if you think that your app needs a presenter that saves its state into a bundle you can easily do that! Mosby internally uses a delegate. You can replace or enhance the default delegate (that works as described above) by providing you custom delegate which could call `presenter.save(Bundle)` and `presenter.restore(Bundle)`. For more details have a look here: http://hannesdorfmann.com/android/mosby-playbook/ 
(scroll down to the end of the page to Tip 22)

**Comment by lurbas** [comment]
Thanks for your response. Well, I understand your approach and respect it. I went through your two articles one more time and have another thought. I want to take the opportunity and share a little inspiration. In my point of view, the ideal architecture would be something between your MVP and MVVM (maybe using mechanism like DataBinding shown at i/o).
To be honest, I don't care about saving state on Presenter, or recreating it. What matters, and what should retain is ViewState/ViewModel (so it should be stored outside Presenter/View). Presenter should be a layer between input from View and Model, but after making thinks done should update ViewModel and doesn't care about View at all. ViewModel after detect internal changes should update View if any is connected, or wait and apply itself on next View which want to bind with this ViewModel.
But all in all, great job :+1:

**Comment by sockeqwe** [comment]
I definitely agree that something between MVP and MVVM would be a good choice and I think Mosbys approach goes (slightly) into this direction. It could be become better once it works with DataBinding  though.

The problem is that you cant reattach the View to the **SAME** Presenter/ViewModel instance easily. You (and I) would like to have something like this:

1. View(Portait) <--> Presenter(Portrait) <--> Background Task (Portrait)
2. Screen orientation changes
3. View (Landscape) <--> Presenter(Portrait) <--> Background Task (Portrait)

With retaining Fragments it's easy and you get exactly the thing as described above.

However, with everything else (not Retaining Fragment) it's not easy to reattach View(Landscape) to Presenter(Portrait). So you have something like this:

1. View(Portait) <--> Presenter(Portrait) <--> Background Task (Portrait)
2. Screen orientation changes
3. View (Landscape) <-- create new presenter instance --> Presenter(Landscape) <--> Background Task (Landscape)

Actually, in Mosby there is something like  `ViewState` in between which is kind of `ViewModel`. It survives Screen orientation changes and gives the user on UI Level the impression that everything is still the same state as before orientation changes:

1. View(Portait) <--> ViewState(Portrait) <--> Presenter(Portrait) <--> Background Task (Portrait)
2. Screen orientation changes
3. View (Landscape) <--> ViewState(Portrait) <-- create new presenter instance --> Presenter(Landscape) <--> Background Task (Landscape)

So the `ViewState` in Mosby is that kind of object you are describing in:
> What matters, and what should retain is ViewState/ViewModel (so it should be stored outside Presenter/View).
ViewState is not ViewModel and it's not Presenter, it's something in between.

If using android services you can also Retain the "background task". It should be easy to reconnect the Presenter to an android service like that:
1. View(Portait) <--> ViewState(Portrait) <--> Presenter(Portrait) <--> Background **Service** (Portrait)
2. Screen orientation changes
3. View (Landscape) <--> ViewState(Portrait) <-- create new presenter instance --> Presenter(Landscape) <--> Background **Service** (Portrait)

Please note that most of the time in my apps make http GET requesst and many popular http frameworks support http request batching. So making a request for the same URL two times (before the first request completes) results in executing the request just one time and inform both callbacks of the first request like Presenter (Portrait) and the second callback like Presenter (Landscape) or the result comes from http cache. Therefore, while working with http usually it's not a big deal if Presenter restarts the request again after screen orientation changes.
