### ISSUE TITLE
Avoid repetitive checks via isViewAttached() using null object pattern

### ISSUE THREAD

**Issue by jenzz** [sockeqwe/mosby#56]
Hey!

I've been experimenting with mosby a little bit this afternoon. Great framework, thanks!
This really makes creating a clean architecture on Android a lot simpler.

One thing I found slightly annoying are the repetitive checks using `isViewAttached()` that are required to ensure the `MvpView` is still attached to the `MvpPresenter` every time you want to update the view. Obviously these checks are necessary since it's the view's responsibility to attach to and detach from the presenter and any asynchronous callback might only return after the view has already been detached. However, I think this can be simplified.

So a common solution to avoid these null-checks before notifying listeners/callbacks is to use the null object pattern, i.e. providing a no-op implementation of the respective interface. Now this gets a bit tricky if generics are involved like in your `MvpPresenter<V extends MvpView>`. However, I think I've come up with a reasonable solution by creating dynamic no-op implementations of those interfaces at runtime using Java's dynamic proxies feature and using a default invocation handler. 

I've created a `MvpBasePresenter2` which makes use of this and also removes the now redundant `isViewAttached()` method.
Here's the [relevant commit](https://github.com/jenzz/mosby/commit/bf7a83a1ce4af42654767fc4ddf281ed4fb043e3) in my fork.

I know that this solution is based on reflection. And reflection is baaaaaaaaad. Some people are allergic to it. However, in my opinion, in this case the cleaner code far outweighs the negligible performance penalty.

Please let me know your thoughts.

**Comment by sockeqwe** [comment]
In general I agree, it's painful to add all those `isViewAttached()` checked.

First let me explain why `MvpBasePresenter` uses a `WeakReference`. Usually there is no need to wrap the `MvpView` in a `WeakReference` because:
 1. Any async call should be canceled in `detachView()`, so that no callback should be invoked afterwards. For instance with `RxJava` and `unsubscribe()` this works like a charm. 

 2. However, there might be scenarios where you don't want to cancel running async background tasks, like using retaining Fragments. But also in that case the Fragment gets detached and reattached temporarily during orientation changes. However, Mosby assumes that every interaction with the view takes place on the main UI Thread. So every interaction with the view from a callback / presenter **must** run on the main UI Thread. Hence it's **not possible** that a callback accesses the view during a screen orientation change, since screen orientation changes run on the main ui thread as well. Therefore, either screen orientation changes run before callback or vice versa, but **never** in parallel.

So why does Mosby's default implementation uses a `WeakReference`?
The only reason why Mosby's default implementation uses a `WeakReference` is that I wanted to avoid memory leaks if other developers misuse Mosby by writing a custom delegate that i.e. forget to call  `presenter.detachView()`. 

Thus at a first glance you might come to the conclusion that `View` can never be `null`. Unfortunately, it can be in case that `View` is detached (i.e. user has closed the activity by pressing back button) but an async running background thread has not been canceled in `detachView()`. i.e. as far as I know Retrofit 1.x has no API to cancel running requests. Therefore, we have to check if `view != null` anyway.

Alright, so back to your suggestion to use the null object pattern. Your implementation looks good  (there is a little issue with WeakReference, I have added a comment in your commit to point out the problem) and I think in that case it reasonable to use reflections. 

But I have in general a problem with the null object pattern in general. I don't like it because usually it only tries to hide other problems (might be an implementation detail like libraries that don't support canceling async threads or a lack of java programming language syntax / expressiveness).

On one hand you are right and those `view != null` checks are pretty annoying. I have to think  about it again, but I think we could try to find a compromise by adding those kind of base presenter, but I see it more as an addition and not as a replacement of `MvpBasePresenter`. However, having a second  null object based `MvpNullObjectBasePresenter` implementation may result in having also a bunch of other presenter implemetation like `RxNullObjectPresenter`, `RetrofitNullObjectPresenter` and so on.

On the other hand that kind of problem could be solved by a Kotlin, where you could replace 

```java
 if (isViewAttached()){
    getView.showContent();
}
```

with 

```kotlin
getView()?showContent()
```

What do you think?

**Comment by IgorGanapolsky** [comment]
So Kotlin solves this problem by internally looking for null Views?  I
didn't know that. Perhaps I should give Kotlin a more serious look.

Igor

**Comment by sockeqwe** [comment]
http://kotlinlang.org/docs/reference/null-safety.html

**Comment by sockeqwe** [comment]
Hi @jenzz  I was wondering if you would allow me to integrate your  dynamic no-op  view code into the next major release?

**Comment by jenzz** [comment]
Sure. That's how open-source works, right?
I'm happy to send over a PR that you can tweak as you see fit.

I think the use of `WeakReference` in the presenter needs to be revised though. I suggest dropping them altogether.
I see the point of being defensive to avoid potential misuse of your library. However, devs should know that for every call to `register()`, `attach()`, `subscribe()` there is most probably a corresponding `unregister()`, `detach()` or `unsubscribe()`. I usually add documentation (Javadoc) to the respective public methods and mention the importance of deregistering to avoid memory leaks.

**Comment by sockeqwe** [comment]
Yes, there is no need for `WeakReference`. 

Could you please also rename the class to  `NullObjectPresenter` (any better naming idea is very welcome) since it will not be a replacement for `MvpBasePresenter` but rather an additional presenter.

**Comment by jenzz** [comment]
Done.

I've also moved the new presenter into the **mvp-common** module since it's an Android-agnostic implementation and there is no need for it to reside in the **mvp** module which is in fact Android-specific.

**Comment by sockeqwe** [comment]
Merged, thanks!

**Comment by CDRussell** [comment]
Hi, I know this issue is a bit old, but seeing as it merged, thought it would still be valid to ask the question.

I wasn't using Mosby in a project, but came up with the exact same solution independently and I tried it out for a while. However, I discovered a large problem with it not handling methods with return types.

I did start going down a similar path to how Mosby accepted it (having the ability to return "default" ints booleans strings etc... but I couldn't solve the problem of having a method on the view which returned a class I defined in my project. In those scenarios, the call to `view.getUser()` or whatever would still inevitably return `null` and subsequently null pointer. 

Did you ever run into this problem, or find a nice solution to it?

My solution for reference: https://medium.com/@trionkidnapper/android-mvp-an-end-to-if-view-null-42bb6262a5d1#.6an16xlhn

Thanks

**Comment by sockeqwe** [comment]
No, this is not solvable.
You simply should never call view getter methods from presenter (view should not offer getter methods at all). Playing ping-pong between view and presenter like `presenter.doSomething()` which then calls `view.getFoo()` is ridiculous. Pass all data needed for the presenter as constructor parameter or as method parameter like `presenter.doSomething(user)`

**Comment by dimsuz** [comment]
I have the similar experience as @sockeqwe. I used to go down this path of having view with getters, even simple ones like `view.getEditTextContent()` and this makes unit-testing rather hard (you have to constantly mock and stub view) and in this case state slowly starts moving to the view and presenter turns out to be tightly coupled with view and presenter logic also tends to start moving to view bit by bit...

Instead what I've found working "right" is to hold all this state in presenter, even if it will result in copying. I.e. initial reasoning is like this "why should I have a copy of `userName` string in presenter if it is already held in `EditText` and I can just call `view.getUserName()` which would get it out of there, and so I wouldn't need an extra variable in presenter..."

But I found that this doesn't work so well. Holding all state in presenter does work though.

**Comment by CDRussell** [comment]
Thanks @sockeqwe @dimsuz; makes a lot of sense.

**Comment by NikitaZhelonkin** [comment]
Should we check for `isViewAttached()` inside view's interactions callback like:
    ```
public void onButtonClick() {
        if(isViewAttached()){
            getView().doSomething();
        }
    }
```
I noticed that in fragments view's onClick callback can be called after onDestroyView, so viewRef can return null and we get NPE
