### ISSUE TITLE
Provide sources automatically

### ISSUE THREAD

**Issue by kokaz** [sockeqwe/mosby#6]
I saw that in some library like OkHttp, source code is provided automatically when we have a dependency to the library. As you include lot of code in different module, I want to have sources directly in my IDE it's easier to handle the framework lifecycle with the sources ! 

Thanks :)

**Comment by sockeqwe** [comment]
[Sources](https://oss.sonatype.org/service/local/repositories/releases/content/com/hannesdorfmann/mosby/core/1.0.0/core-1.0.0-sources.jar) and [javadoc](https://oss.sonatype.org/service/local/repositories/releases/content/com/hannesdorfmann/mosby/core/1.0.0/core-1.0.0-javadoc.jar) are provided through maven central.

The problem is that the library is packed as `.aar` and not as a solid `.jar`. Android Studio is not able to load sources or javadoc for `.aar` files. Don't ask my why. 

https://code.google.com/p/android/issues/detail?id=77425
https://groups.google.com/forum/#!topic/adt-dev/yVPo71O_ZKM


`OkHttp` is packed as a `.jar`. Actually, you can try the `testing module` which is a simple  `.jar`. The sources and javadoc for them will be loaded automatically:
```java
compile  'com.hannesdorfmann.mosby:testing:1.0.0'
```
Try to open `MvpLcePresenterTest` and you will see that sources / javadoc are attached correctly.

You may find this helpful (never used, because I use IntelliJ 14 / Android Studio 1.2 beta which has a build in decompiler):
https://github.com/xujiaao/AARLinkSources
