### ISSUE TITLE
Is it production ready ?

### ISSUE THREAD

**Issue by kokaz** [sockeqwe/mosby#7]
All is in the title :) Do you think the framework is production ready for a large app ?
Thanks !

**Comment by sockeqwe** [comment]
I would say it is.
In fact, in our company we are using an internal fork of mosby successfully in a very large app with over 2 million users:

![kicker](https://cloud.githubusercontent.com/assets/583598/7091863/7fd72394-dfad-11e4-9f47-4acacf4597c3.png)

As you see we have 99,8 % percent of crash free users (the majority of crashes are caused by `OutOfMemory` since we load a lot of images and an awkward third party advertisement sdk) and we still support android 2.3. 

I'm pretty sure we wouldn't have achieved that without a clear mvp architecture.
