### ISSUE TITLE
Some small Graphic issue

### ISSUE THREAD

**Issue by HowardSchmaeu** [sockeqwe/mosby#70]
in Your Mail App: if you pull down ... your mails will be refreshed ... the List and also the small circle comes from the Top UNDER the Toolbar. Also if you scroll down... the List disappear behind the Toolbar...

BUT if u Star an Item and UNSTAR this... the List and the Circle comes from the Top of the Screen 

![image](https://cloud.githubusercontent.com/assets/11573181/8721100/d324e97c-2bb7-11e5-8b92-e4134cc5c543.png)

**Comment by sockeqwe** [comment]
Yeah, not sure what's going on here, but the problem seems to be the star explode  animation.

Sorry, but you are here on your own since it's not Mosby related. You may consider create a new issue in the github repo of the animations I'm using

or 

simply not use the animation and just swap image resource for stared / unstared or something like this.
