### ISSUE TITLE
if i download the whole Project... but i can't build that...

### ISSUE THREAD

**Issue by HowardSchmaeu** [sockeqwe/mosby#73]
i just download the actual Version as .zip File and try to import and build that... but i got 290 Errors :-)
I update also to the newest Tools and Stuff with the SDK Manager... 
did u have ANY Idea ?? 

THX

**Comment by IgorGanapolsky** [comment]
@HowardSchmaeu You should be importing the gradle project in Android
Studio.  In that case it is the top-most build.gradle file in the repo.

**Comment by HowardSchmaeu** [comment]
yes i did... but i got all these errors...

**Comment by sockeqwe** [comment]
which java version do you use? Because there was an issue with java 8 and javadoc?

If you are using java 8 please download 1.1.1 Version and replace the files `maven-push-javalib.gradle` with the current one from master branch: https://github.com/sockeqwe/mosby/blob/master/maven-push-java-lib.gradle

Do the same for `maven-push.gradle`: https://github.com/sockeqwe/mosby/blob/master/maven-push.gradle

**Comment by HowardSchmaeu** [comment]
yes i use the newest java version (8.5??)... and it builds with the Version 1.1.1
What i have to do to get this also with the 1.2.0 Mosby Version?? Back to Java 7 ??

**Comment by sockeqwe** [comment]
just clone latest master branch (or download the zip if you prefer that). It already contains the correct gradle files and should work with java 8

**Comment by HowardSchmaeu** [comment]
Sorry my Friend, that's what i DID yesterday!!! but i does not work... :-(

**Comment by TechFreak** [comment]
If you post the error/stack trace you are seeing we might be able to help
you

**Comment by sockeqwe** [comment]
Ok, i have just pushed the modified gardle script (removed java doc tasks) to master branch. Can you please checkout latest master branch and retry to import it to android studio.

Also do `Build --> Clean Project` and then `Build --> Rebuild` (in main menu).

If that still doesn't work, there might be another problem. In that case please post the whole error stacktrace: run from command line `./gradlew clean build --stacktrace`

**Comment by HowardSchmaeu** [comment]
YEHAAA... it works!!! Thank you!!!

**Comment by sockeqwe** [comment]
I'm still not sure what the problem exactly is. On my machine it works with java 8 (with javadoc tasks) and also travis CI is building with java 8 ...

**Comment by IgorGanapolsky** [comment]
Did you set this in your build.gradle:
`compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }`

**Comment by sockeqwe** [comment]
Hm, as far as I know `JavaVersion.VERSION_1_8` does not work on Android (since byte code has to be java 7 compatible) anyway.

As fas as I know only with some other gradle plugins / hacks like Retrolambda one could specify  `JavaVersion.VERSION_1_8` at all.

As fas As I know no android Hello World project would compile with 
```groovy

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }
```

Hence mosby has set this option explicity to `JavaVersion.VERSION_1_7`

**Comment by IgorGanapolsky** [comment]
@sockeqwe I see.  Well, I use retrolambda, so I am used to putting JavaVersion.VERSION_1_8 - which works perfectly.

**Comment by sockeqwe** [comment]
Makes sense. Thanks for your help!
