### ISSUE TITLE
Missing dependency MvpLceView

### ISSUE THREAD

**Issue by pratamawijaya** [sockeqwe/mosby#93]
![screen shot 2015-10-17 at 7 26 53 pm](https://cloud.githubusercontent.com/assets/2455823/10558774/ad2c920e-7506-11e5-9d6a-8dd783127d68.png)

somehow this afternoon, i can't find MvpLceView after build my apps, there is some change in repository ? 

i have been trying create new project and add at my build.gradle
```
  compile 'com.hannesdorfmann.mosby:mvp:2.0.0'
  compile 'com.hannesdorfmann.mosby:viewstate:2.0.0'
```

but still can't find `MvpLceView`

**Comment by sockeqwe** [comment]
Have your code worked before? Have you migrated recently from Mosby 1.x to Mosby 2.0?  Have you tried to clean and rebuild your project?

Usually this kind of issues occur if you have compilation errors in some other source files that leads to the problem that Android Studio  can't resolve some dependencies correctly. What happens if you simply press the "green play button" to compile and start your App? You will see some errors in android studio I guess. Are there any other compile error issues (not import / class name not found issues)?

**Comment by pratamawijaya** [comment]
yes, my code worked before, i have been trying remove my gradle caches `~/.gradle/caches` but it still not working

i have been trying for running your sample, but in your sample you are not gradle library, it project library, and still working.

**Comment by sockeqwe** [comment]
Has your code worked with Mosby 1.x before and are you facing this problem since updating to Mosby 2.0.0 ?  Have you tried to press the "green play button" in android studio?

Can I checkout your source code? Is it available on github or somewhere else?

**Comment by pratamawijaya** [comment]
ah it solved, i deleted again my gradle caches, then redownload all dependency maybe its my internet problem , right now i can import `import com.hannesdorfmann.mosby.mvp.lce.MvpLceView;` thanks for your fast response, im sorry bother you. Thanks

![screen shot 2015-10-17 at 7 59 19 pm](https://cloud.githubusercontent.com/assets/2455823/10558853/c10b1c5c-7509-11e5-95f3-95c0529e02ed.png)

**Comment by sockeqwe** [comment]
You are welcome! Sometimes deleting the `build` folder also solves that kind of problems
