### ISSUE TITLE
mvp-common dependency on Android stuff

### ISSUE THREAD

**Issue by plenza** [sockeqwe/mosby#94]
Hi Hannes. Just a simple question. 

I'm trying to separate Android app into Android related gradle module and plain old Java one. The Java one would have all the presenters, view interfaces, domain entities and domain business logic. Currently mvp-common uses support annotations, NonNull annotation only as I'm aware of. I can see that you have used SdkHandler from Android Gradle plugin to provide local Maven repo with support annotations jar. But still this means that to build this java module we need to have Sdk installed and Android Gradle plugin + android annotations as dependencies of such 'plain' Java module. Can we get rid of these annotations from mvp-common or do you usually keep your builds dependent on android stuff? 

Thanks for any reply.

**Comment by sockeqwe** [comment]
I see ... I have to think about it and test some things. I will come back to you soon.

Before android gradle plugin 1.2 I used plain java modules as well but Mosby hasn't used android support-annotations at this time. Since 1.2 I use android library project modules instead of plain java modules. The only reason I have used java modules before was to be able to write plain old java unit tests (not instrumentation tests). Since android gradle plugin supports plain old unit tests nowadays I don't see the need of plain old java projects anymore (well, probably the compile time is faster in a plain old java module).

Simply removing annotations might be a solution, however I dislike that approach. Furthermore kotlin uses this annotations for null safety / null checks when interop to java

**Comment by plenza** [comment]
Nah, the more I think about that, the more I'm not really so sure about the real need of creating plain old java lib. Android library is perfectly valid for most if not all use cases. I was just overthinking and forgot about YAGNI. And Kotlin interop is another point for keeping the annotations. So forget about it and please close this issue. Thanks!

**Comment by sockeqwe** [comment]
I will close this for now. However, if more people are facing the same issue I'm willing to reopen it.
